language: node_js

node_js:
  - "0.10"

before_install:
  - sudo add-apt-repository ppa:libreoffice/libreoffice-4-0 --yes
  - sudo apt-get update

install:
  - sudo apt-get install -qq libreoffice
  - npm install

before_script:
  - npm install --dev

script: 
  - ls /tmp/
  - loffice --headless --norestore --nolockcheck --convert-to html --outdir /tmp/ test/samples/test1.docx
  - echo $?
  - ls /tmp/
  - npm test
