language: node_js

node_js:
  - "0.10"

before_install:
  - sudo add-apt-repository ppa:libreoffice/libreoffice-4-1 --yes
  - sudo apt-get update

install:
  - sudo apt-get install -qq libreoffice
  - loffice --version
  - npm install

before_script:
  - npm install --dev

script: 
  - npm test
